namespace: ingress-redirector

## Defaults to nginx
# ingressClassName: "nginx"

ingress:
## Uncomment to choose certificate manager and other annotations
#  annotations:
#    cert-manager.io/cluster-issuer: "letsencrypt-prod"
 
  hosts:
    - host: old-domain.tld

## TLS rules if applicable
#  tls:
#    - secretName: ingress-redirector-certificate
#      hosts:
#        - old-domain.tld

## Set of redirect rules, from is a path, but to is a full URL
redirectRules: []
#  - from: /path
#    to: https://new-domain.tld/newpath
#    code: 301
#  - from: /
#    to: https://new-domain.tld/
#    code: 302

